spring:
  application:
    name: config-server
  profiles:
    active: default
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lucascarabajal/ProjectCloudConfig.git
          default-label: main
          clone-on-start: true
          username: lucascarabajal
          password: ${GIT_TOKEN}

server:
  port: 7777

eureka:
  instance:
    instance-id: "${spring.application.name}:${random.value}"
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka


